spring:
  datasource:
    username: root
    password: 1514327057
    url: jdbc:mysql://192.168.83.149:3306/Kelimall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 10.4.172.172:8848
  application:
    name: Keli-product
mybatis-plus:
  locations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-not-delete-value: 0
      logic-delete-value: 1
server:
  port: 15143