spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.4.172.172:8848
      config:
        name: Keli-gateway

    gateway:
      routes:
        - id: product_route
          uri: lb://Keli-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*), /${segment}
          order: 1
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /renren-fast/${segment}
          order: 2

  main:
    web-application-type: reactive

server:
  port: 88

logging:
  level:
    org.springframework.cloud.gateway: DEBUG